id: P009516
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:35:58.779063
source_metadata:
  id: bdr:W1PD89024
  title: དཀར་མཛེས་རྫོང་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞིའི་ཡིག་རིགས་འདེམས་སྒྲིག ༼༡༽
  author: ''
  volumes:
    eaef2229e47c4ded89677d94c7817586:
      image_group_id: I1KG17053
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
