id: IFA40C217
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:10:35+00:00'
last_modified: '2022-06-08T11:35:04.444956+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD89024
  title: དཀར་མཛེས་རྫོང་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞིའི་ཡིག་རིགས་འདེམས་སྒྲིག ༼༡༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4134':
      image_group_id: I1KG17053
      title: ''
      total_pages: 86
      order: 1
      base_file: 4134.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
